# Form implementation generated from reading ui file 'msgbox_binary.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MsgBoxBinary(object):
    def setupUi(self, MsgBoxBinary):
        MsgBoxBinary.setObjectName("MsgBoxBinary")
        MsgBoxBinary.resize(300, 51)
        self.gridLayout = QtWidgets.QGridLayout(MsgBoxBinary)
        self.gridLayout.setObjectName("gridLayout")
        self.LineEdit_1 = LineEdit(parent=MsgBoxBinary)
        self.LineEdit_1.setObjectName("LineEdit_1")
        self.gridLayout.addWidget(self.LineEdit_1, 0, 0, 1, 1)
        self.SubtitleLabel_symbol = SubtitleLabel(parent=MsgBoxBinary)
        self.SubtitleLabel_symbol.setObjectName("SubtitleLabel_symbol")
        self.gridLayout.addWidget(self.SubtitleLabel_symbol, 0, 1, 1, 1)
        self.LineEdit_2 = LineEdit(parent=MsgBoxBinary)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.gridLayout.addWidget(self.LineEdit_2, 0, 2, 1, 1)

        self.retranslateUi(MsgBoxBinary)
        QtCore.QMetaObject.connectSlotsByName(MsgBoxBinary)

    def retranslateUi(self, MsgBoxBinary):
        _translate = QtCore.QCoreApplication.translate
        MsgBoxBinary.setWindowTitle(_translate("MsgBoxBinary", "Form"))
        self.SubtitleLabel_symbol.setText(_translate("MsgBoxBinary", "?"))
from qfluentwidgets import LineEdit, SubtitleLabel
