# Form implementation generated from reading ui file 'msgbox_intersection.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MsgBoxIntersection(object):
    def setupUi(self, MsgBoxIntersection):
        MsgBoxIntersection.setObjectName("MsgBoxIntersection")
        MsgBoxIntersection.resize(200, 94)
        self.gridLayout_3 = QtWidgets.QGridLayout(MsgBoxIntersection)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.LineEdit_l1 = LineEdit(parent=MsgBoxIntersection)
        self.LineEdit_l1.setObjectName("LineEdit_l1")
        self.gridLayout.addWidget(self.LineEdit_l1, 0, 0, 1, 1)
        self.StrongBodyLabel = StrongBodyLabel(parent=MsgBoxIntersection)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.gridLayout.addWidget(self.StrongBodyLabel, 0, 1, 1, 1)
        self.LineEdit_l2 = LineEdit(parent=MsgBoxIntersection)
        self.LineEdit_l2.setObjectName("LineEdit_l2")
        self.gridLayout.addWidget(self.LineEdit_l2, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.StrongBodyLabel_2 = StrongBodyLabel(parent=MsgBoxIntersection)
        self.StrongBodyLabel_2.setObjectName("StrongBodyLabel_2")
        self.gridLayout_2.addWidget(self.StrongBodyLabel_2, 0, 0, 1, 1)
        self.LineEdit_name = LineEdit(parent=MsgBoxIntersection)
        self.LineEdit_name.setObjectName("LineEdit_name")
        self.gridLayout_2.addWidget(self.LineEdit_name, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)

        self.retranslateUi(MsgBoxIntersection)
        QtCore.QMetaObject.connectSlotsByName(MsgBoxIntersection)

    def retranslateUi(self, MsgBoxIntersection):
        _translate = QtCore.QCoreApplication.translate
        MsgBoxIntersection.setWindowTitle(_translate("MsgBoxIntersection", "Form"))
        self.LineEdit_l1.setPlaceholderText(_translate("MsgBoxIntersection", "线名"))
        self.StrongBodyLabel.setText(_translate("MsgBoxIntersection", "与"))
        self.LineEdit_l2.setPlaceholderText(_translate("MsgBoxIntersection", "线名"))
        self.StrongBodyLabel_2.setText(_translate("MsgBoxIntersection", "交于点"))
        self.LineEdit_name.setPlaceholderText(_translate("MsgBoxIntersection", "仅一个大写字母"))
from qfluentwidgets import LineEdit, StrongBodyLabel
