# Form implementation generated from reading ui file 'msgbox_point.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MsgBoxPoint(object):
    def setupUi(self, MsgBoxPoint):
        MsgBoxPoint.setObjectName("MsgBoxPoint")
        MsgBoxPoint.resize(200, 129)
        self.gridLayout = QtWidgets.QGridLayout(MsgBoxPoint)
        self.gridLayout.setObjectName("gridLayout")
        self.StrongBodyLabel = StrongBodyLabel(parent=MsgBoxPoint)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.gridLayout.addWidget(self.StrongBodyLabel, 0, 0, 1, 1)
        self.LineEdit_name = LineEdit(parent=MsgBoxPoint)
        self.LineEdit_name.setObjectName("LineEdit_name")
        self.gridLayout.addWidget(self.LineEdit_name, 0, 1, 1, 1)
        self.StrongBodyLabel_2 = StrongBodyLabel(parent=MsgBoxPoint)
        self.StrongBodyLabel_2.setObjectName("StrongBodyLabel_2")
        self.gridLayout.addWidget(self.StrongBodyLabel_2, 1, 0, 1, 1)
        self.LineEdit_x = LineEdit(parent=MsgBoxPoint)
        self.LineEdit_x.setObjectName("LineEdit_x")
        self.gridLayout.addWidget(self.LineEdit_x, 1, 1, 1, 1)
        self.StrongBodyLabel_3 = StrongBodyLabel(parent=MsgBoxPoint)
        self.StrongBodyLabel_3.setObjectName("StrongBodyLabel_3")
        self.gridLayout.addWidget(self.StrongBodyLabel_3, 2, 0, 1, 1)
        self.LineEdit_y = LineEdit(parent=MsgBoxPoint)
        self.LineEdit_y.setObjectName("LineEdit_y")
        self.gridLayout.addWidget(self.LineEdit_y, 2, 1, 1, 1)

        self.retranslateUi(MsgBoxPoint)
        QtCore.QMetaObject.connectSlotsByName(MsgBoxPoint)

    def retranslateUi(self, MsgBoxPoint):
        _translate = QtCore.QCoreApplication.translate
        MsgBoxPoint.setWindowTitle(_translate("MsgBoxPoint", "Form"))
        self.StrongBodyLabel.setText(_translate("MsgBoxPoint", "名字"))
        self.LineEdit_name.setPlaceholderText(_translate("MsgBoxPoint", "仅一个大写字母"))
        self.StrongBodyLabel_2.setText(_translate("MsgBoxPoint", "横坐标"))
        self.LineEdit_x.setPlaceholderText(_translate("MsgBoxPoint", "留空为设未知数"))
        self.StrongBodyLabel_3.setText(_translate("MsgBoxPoint", "纵坐标"))
        self.LineEdit_y.setPlaceholderText(_translate("MsgBoxPoint", "留空为设未知数"))
from qfluentwidgets import LineEdit, StrongBodyLabel
