# Form implementation generated from reading ui file 'msgbox_point_on_line.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MsgBoxPointOnLine(object):
    def setupUi(self, MsgBoxPointOnLine):
        MsgBoxPointOnLine.setObjectName("MsgBoxPointOnLine")
        MsgBoxPointOnLine.resize(200, 135)
        self.gridLayout_4 = QtWidgets.QGridLayout(MsgBoxPointOnLine)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.StrongBodyLabel = StrongBodyLabel(parent=MsgBoxPointOnLine)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.gridLayout.addWidget(self.StrongBodyLabel, 0, 0, 1, 1)
        self.LineEdit_name = LineEdit(parent=MsgBoxPointOnLine)
        self.LineEdit_name.setObjectName("LineEdit_name")
        self.gridLayout.addWidget(self.LineEdit_name, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.StrongBodyLabel_2 = StrongBodyLabel(parent=MsgBoxPointOnLine)
        self.StrongBodyLabel_2.setObjectName("StrongBodyLabel_2")
        self.gridLayout_2.addWidget(self.StrongBodyLabel_2, 0, 0, 1, 1)
        self.LineEdit_l = LineEdit(parent=MsgBoxPointOnLine)
        self.LineEdit_l.setObjectName("LineEdit_l")
        self.gridLayout_2.addWidget(self.LineEdit_l, 0, 1, 1, 1)
        self.StrongBodyLabel_3 = StrongBodyLabel(parent=MsgBoxPointOnLine)
        self.StrongBodyLabel_3.setObjectName("StrongBodyLabel_3")
        self.gridLayout_2.addWidget(self.StrongBodyLabel_3, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.StrongBodyLabel_4 = StrongBodyLabel(parent=MsgBoxPointOnLine)
        self.StrongBodyLabel_4.setObjectName("StrongBodyLabel_4")
        self.gridLayout_3.addWidget(self.StrongBodyLabel_4, 0, 0, 1, 1)
        self.LineEdit_x = LineEdit(parent=MsgBoxPointOnLine)
        self.LineEdit_x.setObjectName("LineEdit_x")
        self.gridLayout_3.addWidget(self.LineEdit_x, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 1)

        self.retranslateUi(MsgBoxPointOnLine)
        QtCore.QMetaObject.connectSlotsByName(MsgBoxPointOnLine)

    def retranslateUi(self, MsgBoxPointOnLine):
        _translate = QtCore.QCoreApplication.translate
        MsgBoxPointOnLine.setWindowTitle(_translate("MsgBoxPointOnLine", "Form"))
        self.StrongBodyLabel.setText(_translate("MsgBoxPointOnLine", "点"))
        self.LineEdit_name.setPlaceholderText(_translate("MsgBoxPointOnLine", "仅一个大写字母"))
        self.StrongBodyLabel_2.setText(_translate("MsgBoxPointOnLine", "在线"))
        self.LineEdit_l.setPlaceholderText(_translate("MsgBoxPointOnLine", "线名"))
        self.StrongBodyLabel_3.setText(_translate("MsgBoxPointOnLine", "上"))
        self.StrongBodyLabel_4.setText(_translate("MsgBoxPointOnLine", "横坐标"))
        self.LineEdit_x.setPlaceholderText(_translate("MsgBoxPointOnLine", "留空为设未知数"))
from qfluentwidgets import LineEdit, StrongBodyLabel
